name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: executing remote ssh commands using private key
          uses: appleboy/ssh-action@master
          with:
            host: 106.52.196.104
            username: ubuntu
            key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
            port: 22
            script: |
              cd /home/ubuntu/douke-admin
              git fetch 
              git reset --hard origin/main
              npm i
              npm run build
